# Load ~/dotfiles/shared/ bash_prompt, exports, aliases and functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/dotfiles/shared/{bash_prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Prefer US English and use UTF-8
export LC_ALL="C"
export LANG="en_US"
#export LC_COLLATE="C"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

export CLICOLOR=1

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Some handy Kace specific commands
alias codesniffer='phpcs -p --standard=/home/clang/workspace/CodeSniffer/build/Symfony2/ /home/clang/workspace/m500; phpcs -p --standard=/home/clang/workspace/CodeSniffer/build/Symfony2/ /home/clang/workspace/mx00;'
alias logs="sudo tail -f /home/clang/workspace/m500/Symfony/app/logs/dev.log /var/log/apache2/error.log | grep -i -w '\(critical\|error\|app.ALERT\)'"
